---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: "chromium - check chromium package status"
      ansible.builtin.package:
        name: "chromium"
        state: "installed"
      check_mode: true
      register: pkg_status

    - name: "chromium - test chromium package is installed"
      ansible.builtin.assert:
        that:
          - not pkg_status.changed
