---
install_packages:
    - name: curl
    - name: wget
    - name: zopfli
    - name: libevent-dev
    - name: libxslt-dev
    - name: libxml2-dev
    - name: remmina
    - name: nscd
    - name: flameshot
    - name: bottom

external_packages:
    - repo: ppa:ultradvorka/ppa
      state: present
