---
install_packages:
    - name: util-linux-user
    - name: curl
    - name: wget
    - name: zopfli
    - name: rpm-build
    - name: libevent-devel
    - name: libxslt-devel
    - name: libxml2-devel
    - name: ansible-lint
    - name: remmina
    - name: tilix
    - name: hstr
    - name: nscd
    - name: python3-libselinux
    - name: flameshot
    - name: okular

external_packages: []
