---
- name: include distro-specific tasks
  include_vars: "{{ ansible_os_family }}.yml"

- name: install chromium
  package:
      name: "{{ item.name }}"
      state: "{{ item.state | default('present') }}"
  with_items: "{{ chromium_package | default({}) }}"
  become: yes
