---
- name: include distro-specific tasks
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: install chromium
  ansible.builtin.package:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ chromium_package | default({}) }}"
  become: true
