---
- name: include distro-specific tasks
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: install chromium
  ansible.builtin.include_role:
    name: syspackage
  vars:
    os_packages: "{{ chromium_package | default({}) }}"
