---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: "packages - check curl package status"
      ansible.builtin.package:
        name: "curl"
        state: "installed"
      check_mode: true
      register: pkg_status

    - name: "packages - test curl package is installed"
      ansible.builtin.assert:
        that:
          - not pkg_status.changed

    - name: "packages - check that curlrc exists"
      ansible.builtin.stat:
        path: "/root/.config/curl/curlrc"
      register: stat_result

    - name: "packages - test curlrc exists"
      ansible.builtin.assert:
        that:
          - stat_result.stat.exists
