---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  ansible-lint
platforms:
  - name: fedora
    image: geerlingguy/docker-fedora36-ansible:latest
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../../../roles
verifier:
  name: ansible
