---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: mxmaster - check that logid.cfg exists
      ansible.builtin.stat:
        path: /etc/logid.cfg
      register: stat_result

    - name: mxmaster - test logid.cfg exists
      ansible.builtin.assert:
        that:
          - stat_result.stat.exists
