---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: mxmaster - check logiops service
      ansible.builtin.systemd:
        name: logid.service
        daemon_reload: yes
        enabled: yes
      check_mode: yes
      register: pkg_status

    - name: mxmaster - test logiops service is installed
      ansible.builtin.assert:
        that:
          - not pkg_status.changed

    - name: mxmaster - check that logid.cfg exists
      ansible.builtin.stat:
        path: /etc/logid.cfg
      register: stat_result

    - name: mxmaster - test logid.cfg exists
      ansible.builtin.assert:
        that:
          - stat_result.stat.exists

    - name: mxmaster - check that build directory doesnt exist
      ansible.builtin.stat:
        path: /tmp/hidpp/build
      register: stat_result

    - name: mxmaster - test build directory doesnt exist
      ansible.builtin.assert:
        that:
          - not stat_result.stat.exists
