---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: "ruby - check for data directory"
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.local/share/rbenv"
      register: stat_result

    - name: "ruby - check rbenc directory exists"
      ansible.builtin.assert:
        that:
          - stat_result.stat.exists
