---
- name: install needed system packages
  pacman:
      name: "{{ item.name }}"
      state: '{{ item.state | default("present") }}'
      update_cache: yes
  with_items: "{{ os_packages }}"
  become: yes
