---
- name: install needed system packages
  apt:
      name: "{{ item.name }}"
      state: '{{ item.state | default("present") }}'
      #   install_recommends: yes
      update_cache: yes
  with_items: "{{ os_packages }}"
  become: yes
