---
- name: install copr repos
  community.general.copr:
    state: '{{ item.state | default("enabled") }}'
    name: "{{ item.repo }}"
  with_items: "{{ external_repos }}"
  become: true

- name: install needed system packages
  dnf:
    name: "{{ item.name }}"
    state: '{{ item.state | default("present") }}'
  with_items: "{{ os_packages }}"
  become: true
