---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
      - name: "polybar - check polybar package status"
        package:
            name: "polybar"
            state: "installed"
        check_mode: yes
        register: pkg_status

      - name: "polybar - test polybar package is installed"
        assert:
            that:
                - not pkg_status.changed

      - name: "polybar - check that config exists"
        stat:
            path: "/root/.config/polybar/config"
        register: stat_result

      - name: "polybar - test config exists"
        assert:
            that:
                - stat_result.stat.exists

      - name: "polybar - check that MaterialIcon exists"
        stat:
            path: "/root/.local/share/fonts/MaterialIcon"
        register: stat_result

      - name: "polybar - test MaterialIcon exists"
        assert:
            that:
                - stat_result.stat.exists
