---
# - name: classify hosts depending on their OS distribution
#   group_by:
#   key: os_{{ ansible_facts['distribution'] }}

- name: setup system
  hosts: all
  connection: local
  roles:
    - role: xdg_dirs
      tags: [xdg, bootstrap]
    - role: fish
      tags: [fish, boostrap]
    - role: alacritty
      tags: [applications, alacritty]
    - role: aws
      tags: [aws, bootstrap]
    - role: chromium
      tags: [applications, chromium]
    - role: git
      tags: [git, bootstrap]
    - role: go
      tags: [go, bootstrap]
    - role: kube
      tags: [kube, bootstrap]
    - role: mxmaster
      tags: mxmaster
    - role: node
      tags: [node, bootstrap]
    - role: packages
      tags: [packages, bootstrap]
    - role: powersave
      tags: powersave
    - role: python
      tags: [python, boostrap]
    - role: ruby
      tags: [ruby, boostrap]
    - role: rust
      tags: [rust, boostrap]
    - role: taskwarrior
      tags: [taskwarrior]
    - role: tmux
      tags: [applications, tmux]
    - role: vim
      tags: [applications, vim]
    - role: vscode
      tags: [vscode]
    - role: zsh
      tags: [zsh]

- name: setup Gnome DE
  hosts: gnome
  connection: local
  roles:
    - role: gnome
      tags: gnome
