---
# - name: classify hosts depending on their OS distribution
#   group_by:
#   key: os_{{ ansible_facts['distribution'] }}

- name: setup system
  hosts: all
  connection: local
  roles:
    - role: xdg_dirs
      tags: bootstrap
    - role: alacritty
      tags: alacritty
    - role: aws
      tags: [aws, bootstrap]
    - role: chromium
      tags: chromium
    # Docker has issues, need to find a better way
    # - role: docker
    #   tags: docker
    - role: git
      tags: [git, bootstrap]
    - role: go
      tags: [go, bootstrap]
    - role: kube
      tags: [kube, bootstrap]
      become: true
    - role: mxmaster
      tags: mxmaster
    - role: node
      tags: [node, bootstrap]
    - role: packages
      tags: [packages, bootstrap]
    - role: powersave
      tags: powersave
    - role: linux-system-roles.tuned
      tags: [tuned, powersave]
      become: true
    - role: python
      tags: [python, boostrap]
    - role: ruby
      tags: [ruby, boostrap]
    - role: rust
      tags: [rust, boostrap]
    - role: taskwarrior
      tags: taskwarrior
    - role: tmux
      tags: tmux
    - role: vim
      tags: vim
    - role: vscode
      tags: vscode
    - role: zsh
      tags: [zsh, boostrap]

- name: setup Gnome DE
  hosts: gnome
  connection: local
  roles:
    - role: gnome
      tags: gnome
