---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  ansible-lint
platforms:
  - name: fedora
    image: geerlingguy/docker-fedora34-ansible:latest
provisioner:
  name: ansible
verifier:
  name: ansible
