---
# tasks file for packages
- name: include OS specific vars
  include_vars: "{{ ansible_os_family }}.yml"

- name: install packages
  include_role:
    name: syspackage
  vars:
    os_packages: "{{ install_packages }}"
    external_repos: "{{ external_packages }}"

- name: make directories base configs
  file:
    path: "{{ ansible_user_dir }}/.config/{{ item.path }}"
    state: directory
    mode: 0755
  with_items: "{{ symlink_files }}"

- name: copy base configs
  copy:
    src: "{{ item.file }}"
    dest: "{{ ansible_user_dir }}/.config/{{ item.path }}/"
    mode: preserve
  with_items: "{{ symlink_files }}"

- name: include OS specific tasks
  include_tasks: "{{ ansible_os_family }}.yml"
