---
# tasks file for packages
- name: include OS specific vars
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: enable rpm fusion packages
  ansible.builtin.include_role:
    name: robertdebock.rpmfusion
  when: ansible_os_family == 'RedHat'

- name: install packages
  ansible.builtin.include_role:
    name: syspackage
  vars:
    os_packages: "{{ install_packages }}"
    external_repos: "{{ external_packages }}"

- name: make directories base configs
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/{{ item.path }}"
    state: directory
    mode: 0755
  with_items: "{{ symlink_files }}"

- name: copy base configs
  ansible.builtin.copy:
    src: "{{ item.file }}"
    dest: "{{ ansible_user_dir }}/.config/{{ item.path }}/"
    mode: preserve
  with_items: "{{ symlink_files }}"

- name: include OS specific tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"
