---
# tasks file for packages
- name: include distro-specific vars
  include_vars: "{{ ansible_os_family }}.yml"

- name: Enable external repos (Debian)
  apt_repository:
      repo: "{{ item.repo | default('') }}"
      state: "{{ item.state | default('present') }}"
  loop: "{{ external_packages | default([]) }}"
  become: yes
  when:
      - ansible_os_family == 'Debian'

- name: make directories base configs
  file:
      path: "{{ ansible_user_dir }}/.config/{{ item.path }}"
      state: directory
      mode: 0755
  with_items: "{{ symlink_files }}"

- name: copy base configs
  copy:
      src: "{{ item.file }}"
      dest: "{{ ansible_user_dir }}/.config/{{ item.path }}/"
      mode: preserve
  with_items: "{{ symlink_files }}"
