---
- name: improve DNF Performances
  ansible.builtin.blockinfile:
    path: /etc/dnf/dnf.conf
    create: true
    block: |
      deltarpm=true
      fastestmirror=true
      max_parallel_downloads={{ ansible_processor_vcpus }}
    mode: 0644
  become: true
