- name: include OS specific vars
  include_vars: "{{ ansible_os_family }}.yml"

- name: install xorg package
  include_role:
    name: syspackage
  vars:
    os_packages: "{{ xorg_packages }}"

- name: make sure destination for templates exists
  file:
    path: "{{ ansible_user_dir }}/.config/X11"
    state: directory
    mode: 0755

- name: setup xinitrc config file
  template:
    src: xinitrc.j2
    dest: "{{ ansible_user_dir }}/.config/X11/xinitrc"
    mode: preserve
