---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: gather package facts
      package_facts:
        manager: auto

    - name: xorg - test xorg package is installed
      assert:
        that: "'{{ item }}' in ansible_facts.packages"
      with_items:
        - xorg*

    - name: "xorg - check that xinitrc exists"
      stat:
        path: "/root/.config/X11/xinitrc"
      register: stat_result

    - name: "xorg - test xinitrc exists"
      assert:
        that:
          - stat_result.stat.exists