---
# handlers file for mxmaster
- name: reload udev # noqa 503 305
  ansible.builtin.command: udevadm control --reload
  become: true
  when: udev.stat.exists

- name: trigger udev # noqa 305
  ansible.builtin.command: udevadm trigger
  become: true
  when: udev.stat.exists

- name: reload logiops
  ansible.builtin.systemd:
    name: logid.service
    daemon_reload: true
    enabled: true
    state: reloaded
  become: true
  when: ansible_facts.virtualization_type | default('') not in ['docker', 'container', 'containerd']
