---
collections:
  - name: community.general
roles:
  - src: geerlingguy.docker
  - src: aruhier.ansible_role_tlp
  - src: gantsign.visual-studio-code
  - src: hurricanehrndz.rustup
  - src: robertdebock.rpmfusion
