---
collections:
  - name: community.general
roles:
  - src: linux-system-roles.tuned
  - src: geerlingguy.docker
  - src: aruhier.ansible_role_tlp
  - src: jaredhocutt.google_chrome
  - src: gantsign.visual-studio-code
  - src: hurricanehrndz.rustup
  - src: robertdebock.rpmfusion
  # - src: zaxos.glances-ansible-role
