---
- name: clone lastest (logiops) # noqa 503
  ansible.builtin.git:
    repo: https://github.com/PixlOne/logiops.git
    dest: "/tmp/logiops"
    update: true
    accept_hostkey: true
    version: "master"
  register: logiops

- name: make build directory (logiops) # noqa 503
  ansible.builtin.file:
    path: /tmp/logiops/build
    state: directory
    mode: 0755
  when: logiops.changed

- name: run cmake build from sources (logiops) # noqa 503 305
  ansible.builtin.shell: cmake ..
  args:
    chdir: "/tmp/logiops/build"
  when: logiops.changed

- name: run make from sources (logiops) # noqa 503
  ansible.builtin.make:
    chdir: "/tmp/logiops/build"
  when: logiops.changed

- name: run make install from sources (logiops) # noqa 503
  ansible.builtin.make:
    chdir: "/tmp/logiops/build"
    target: install
  become: true
  when: logiops.changed

- name: copy logid.cfg to /etc/ # noqa 503
  ansible.builtin.copy:
    src: logid.cfg
    dest: /etc/logid.cfg
    mode: preserve
  become: true
  notify:
    - reload logiops

- name: clean up build
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/logiops/build
    - /tmp/hidpp/build
