---
- name: include OS specific vars
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: install needed system packages
  ansible.builtin.include_role:
    name: syspackage
  vars:
    os_packages: "{{ mxmaster_packages }}"

- name: run logiops tasks
  ansible.builtin.include_tasks: logiops.yml
# - include_tasks: libratbag.yml
