---
- name: include OS specific vars
  include_vars: "{{ ansible_os_family }}.yml"

- name: install needed system packages
  include_role:
    name: syspackage
  vars:
    os_packages: "{{ mxmaster_packages }}"

- include_tasks: logiops.yml
# - include_tasks: libratbag.yml
