---
- name: include distro-specific vars
  include_vars: "{{ ansible_os_family }}.yml"

- name: install bspwm packages
  include_role:
    name: syspackage
  vars:
    os_packages: "{{ bspwm_packages }}"

- name: make sure destination for templates exists
  file:
    path: "{{ ansible_user_dir }}/.config/bspwm"
    state: directory
    mode: 0755

- name: copy configs to directory
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.config/bspwm/"
    mode: preserve
  with_fileglob:
    - files/*
