---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: gather package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: aws - test aws-cli package is installed
      ansible.builtin.assert:
        that: "'{{ item }}' in ansible_facts.packages"
      with_items:
        - aws-cli

    - name: "aws - check that aws directory exists"
      ansible.builtin.stat:
        path: "/root/.config/aws"
      register: stat_result

    - name: "aws - test aws directory exists"
      ansible.builtin.assert:
        that:
          - stat_result.stat.exists
