---
- name: powersave options for wifi (Dell 5520)
  copy:
      content: |
          options wlwifi bt_coex_active=0 power_save=1 power_level=5
      dest: /etc/modprobe.d/wifi_5520.conf
      mode: "0644"
      owner: root
      group: root
  become: yes

- name: intel graphics power saving (Dell 5520)
  copy:
      content: |
          options i915 modeset=1 enable_rc6=1 enable_fbc=1 lvds_downclock=1 disable_power_well=0 fastboot=1
      dest: /etc/modprobe.d/i915_5520.conf
      mode: "0644"
      owner: root
      group: root
  become: yes

- name: set options for Dell laptop
  copy:
      content: |
          options dell-smm-hwmon ignore_dmi=1
      dest: /etc/modprobe.d/dell_5520.conf
      mode: "0644"
      owner: root
      group: root
  become: yes

- name: intel sound power saving
  copy:
      content: |
          options snd_hda_intel power_save=1 power_save_controller=Y
      dest: /etc/modprobe.d/snd_hda_intel_5520.conf
      mode: "0644"
      owner: root
      group: root
  become: yes
  notify: Update Grub and Initramfs
