---
- name: stat computer model
  shell: "dmidecode --type system | grep 'Product Name' | sed 's/\tProduct Name: //'"
  register: computerstat
  become: true

- include_tasks: dell5520.yml
  when: computerstat.stdout == "'Precision 5520' in computerstat.stdout"

- include_tasks: dell5550.yml
  when: "'Precision 5550' in computerstat.stdout"
