---
- name: stat computer model
  ansible.builtin.command: "dmidecode -s system-product-name"
  register: computerstat
  when: setup_dell
  become: true

- ansible.builtin.include_tasks: dell5520.yml
  when: ("'Precision 5520' in computerstat.stat.stdout" and setup_dell)

- ansible.builtin.include_tasks: dell5550.yml
  when: ("'Precision 5550' in computerstat.stat.stdout" and setup_dell)
