---
- name: stat computer model
  ansible.builtin.command: "dmidecode -s system-product-name"
  register: computerstat
  when: setup_dell
  become: true

- ansible.builtin.include_tasks: dell5520.yml
  when: computerstat.stdout.find('Precision 5520') != -1

- ansible.builtin.include_tasks: dell5550.yml
  when: computerstat.stdout.find('Precision 5550') != -1
