---
- include_tasks: powersave.yml
  when: install_powersave

- include_tasks: tlp.yml
  when: install_powersave

- include_tasks: dell.yml
  when: install_powersave
  
- name: stat computer cpu
  shell: dmidecode | grep -A3 '^Socket Designation'
  register: computercpu
  become: yes

- include_tasks: modprobe.yml
  when:
     - "'Intel' in computercpu.stdout"
     - install_powersave
