---
- ansible.builtin.include_tasks: powersave.yml
  when: install_powersave

# - ansible.builtin.include_tasks: tlp.yml
#   when: install_powersave

- ansible.builtin.include_tasks: dell.yml
  when: setup_dell

- name: stat computer cpu
  ansible.builtin.command: "dmidecode -s processor-manufacturer"
  register: computercpu
  when: install_powersave
  changed_when: false
  become: true

- ansible.builtin.include_tasks: modprobe.yml
  when: ("'Intel' in computercpu.stat.stdout" and install_powersave)

- name: get mounts from /etc/mtab
  ansible.builtin.command: cat /etc/mtab
  changed_when: false
  register: mount_options

- name: print return of mount_options
  ansible.builtin.debug:
    var: mount_options.stdout_lines

- name: Ensure fstab uses nodiratime and noatime
  ansible.builtin.mount:
    path: "{{ item.split(' ')[1] }}"
    state: mounted
    fstype: "{{ item.split(' ')[2] }}"
    src: "{{ item.split(' ')[0] }}"
    opts: "{{ item.split(' ')[3].split(',') | union(['nodiratime noatime']) | unique | join(',') }}"
  with_items: "{{ mount_options.stdout_lines }}"
  when:
    - item.split(" ")[1] in  ["/", "/boot", "/home"] and "noatime,nodiratime" not in item.split(" ")[3]
  become: true

- name: load IO Schedulers at boot
  ansible.builtin.blockinfile:
    path: /etc/modules-load.d/iosched.conf
    create: true
    block: |
      bfq
      mq-deadline
      kyber-iosched
    mode: 644
  become: true
