---
- name: install powersaving packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: '{{ item.state | default("present") }}'
  become: true
  with_items: "{{ powersave_packages }}"
  notify:
    - detect_sensors

- name: enable powersaving services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
  become: true
  with_items:
    - fstrim.timer
    - thermald.service
  register: services_created
  notify:
    - restart_service
