---
- name: install taskwarrior
  ansible.builtin.package:
    name: task
    state: present
  become: true

- name: install bugwarrior
  ansible.builtin.pip:
    name: bugwarrior
    extra_args: --user

- name: make sure destination for templates exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/task/"
    state: directory
    mode: 0755

- name: copy configs to directory
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.config/task/"
    mode: preserve
  with_fileglob:
    - files/*
