---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint -c $ZSH/.yamllint .
  ansible-lint
  flake8

platforms:
  - name: fedora
    image: geerlingguy/docker-fedora36-ansible:latest
provisioner:
  name: ansible

verifier:
  name: ansible

scenario:
  name: default
