---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: gather package facts
      package_facts:
        manager: auto

    - name: bspwm - test bspwm package is installed
      assert:
        that: "'{{ item }}' in ansible_facts.packages"
      with_items:
        - bspwm

    - name: "bspwm - check that bspwmrc exists"
      stat:
        path: "/root/.config/bspwm/bspwmrc"
      register: stat_result

    - name: "bspwm - test bspwmrc exists"
      assert:
        that:
          - stat_result.stat.exists
