---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
      - name: "lightdm - check lightdm package status"
        package:
            name: "lightdm"
            state: "installed"
        check_mode: yes
        register: pkg_status

      - name: "lightdm - test lightdm package is installed"
        assert:
            that:
                - not pkg_status.changed

      - name: "lightdm - check that lightdm.conf exists"
        stat:
            path: "/etc/lightdm/lightdm.conf"
        register: stat_result

      - name: "lightdm - test lightdm.conf exists"
        assert:
            that:
                - stat_result.stat.exists

      - name: "lightdm - check that lightdm-webkit2-greeter.conf exists"
        stat:
            path: "/etc/lightdm/lightdm-webkit2-greeter.conf"
        register: stat_result

      - name: "lightdm - test lightdm-webkit2-greeter.conf exists"
        assert:
            that:
                - stat_result.stat.exists
