#!/bin/sh

#------------------------------
# Functions
#------------------------------
command_exists() {
  command -v "$@" >/dev/null 2>&1
}

#------------------------------
# Start processes
#------------------------------
command_exists dunst && dunst &
command_exists picom && picom &
command_exists polybar && polybar main &
command_exists feh && feh --bg-fill $HOME/.config/dotfiles/assets/wallpaper2.jpg &
sxhkd &

bspc config border_width                      0
bspc config window_gap                        20
bspc config top_padding                       30
bspc config bottom_padding                    30
bspc config left_padding                      0
bspc config right_padding                     0

bspc config remove_disabled_monitors          true
bspc config remove_unplugged_monitors         true

bspc config split_ratio                       0.52
bspc config borderless_monocle                true
bspc config gapless_monocle                   true
bspc config focus_follows_pointer             true

bspc config pointer_modifier                  mod4
bspc config pointer_action1                   move
bspc config pointer_action2                   resize_side
bspc config pointer_action3                   resize_corner

bspc rule -a Zathura state=tiled

monitors=$(bspc query -M)
num_monitors=$( echo "$monitors" | wc -l )

min=1
mon=1

for monitor in $( echo ${monitors} ) ; do
  div=$((10 / $num_monitors))
  bspc monitor ${monitor} -n $mon -d $(seq -f "$mon/%g" $min $(($div*$mon)))
  min=$(($min+$div))
  let mon++
done
