---
# handlers file for powersave

- name: restart_service
  systemd:
      name: "{{ item.name }}"
      state: restarted
      daemon_reload: yes
  when: item.changed
  with_items: "{{ services_created.results }}"
  become: yes

- name: detect_sensors
  shell: /usr/sbin/sensors-detect < /dev/null
  ignore_errors: yes
  become: yes

- name: update initrd
  command: dracut -f
  become: yes
