---
- name: include OS specific vars
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: install needed system packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ python_system_packages }}"
  become: true

- ansible.builtin.include_tasks: pyenv.yml
  loop: "{{ pyenv_versions }}"
  loop_control:
    loop_var: pip_package_loop
