---
- name: include OS specific vars
  include_vars: "{{ ansible_os_family }}.yml"

- name: install python packages
  include_tasks: "package/{{ ansible_os_family }}.yml"

- include_tasks: pyenv.yml
  loop: "{{ pyenv_versions }}"
  loop_control:
      loop_var: pip_package_loop
