---
gnome_shell_version: "40.0"

gnome_extension_path: "{{ ansible_user_dir }}/.local/share/gnome-shell/extensions"

gnome_profile_path: "/{{ ansible_user_dir }}/.config/dotfiles/assets/profile.jpg"

gnome_profile_checksum: "aebfa46486ad50c6ccfa0ba5e326c921"

gnome_background: "'file:///{{ ansible_user_dir }}/.config/dotfiles/assets/wallpaper.jpg'"

gnome_themes:
  - url: https://github.com/ZorinOS/zorin-desktop-themes/archive/refs/tags/3.4.3.zip
    name: "zorin-desktop-themes-3.4.3"
    theme_folder: "zorin-desktop-themes-3.4.3/ZorinBlue-Dark"

gnome_fonts:
  - url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/FiraCode.zip"
    name: "FiraCode"
    fonts: "*.ttf"
  - url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/FiraMono.zip"
    name: "FiraMono"
    fonts: "*.ttf"
  - url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/IBMPlexMono.zip"
    name: "BlexMono"
    fonts: "*.ttf"
  - url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/JetBrainsMono.zip"
    name: "JetBrainsMono"
    fonts: "*.ttf"

gnome_files:
  - src: gtk3_settings.j2
    dest: "{{ ansible_user_dir }}/.config/gtk-3.0/settings.ini"
  - src: gtk4_settings.j2
    dest: "{{ ansible_user_dir }}/.config/gtk-4.0/settings.ini"
  - src: bookmarks.j2
    dest: "{{ ansible_user_dir }}/.config/gtk-3.0/bookmarks"
  - src: bookmarks.j2
    dest: "{{ ansible_user_dir }}/.config/gtk-4.0/bookmarks"

gnome_config_gsettings:
  - schema: org.gnome.software
    key: first-run
    value: "false"
  - schema: org.gnome.desktop.interface
    key: clock-show-date
    value: "true"
  - schema: org.gnome.desktop.interface
    key: show-battery-percentage
    value: "true"
  - schema: org.gnome.login-screen
    key: banner-message-enable
    value: "true"
  - schema: org.gnome.login-screen
    key: banner-message-text
    value: "'With great power comes great responsibility'"
  - schema: org.gnome.settings-daemon.plugins.color
    key: night-light-enabled
    value: "true"
  - schema: org.gnome.desktop.interface
    key: clock-format
    value: "'12h'"
  - schema: org.gnome.desktop.wm.preferences
    key: button-layout
    value: "'appmenu:minimize,maximize,close'"
  - schema: org.gnome.desktop.interface
    key: document-font-name
    value: "'Cantarell 11'"
  - schema: org.gnome.desktop.interface
    key: font-name
    value: "'Cantarell 11'"
  - schema: org.gnome.desktop.interface
    key: icon-theme
    value: "'{{ theme }}'"
  - schema: org.gnome.desktop.interface
    key: gtk-theme
    value: "'{{ theme }}'"
  - schema: org.gnome.desktop.interface
    key: monospace-font-name
    value: "'{{ font }} 14'"
  - schema: org.gnome.desktop.interface
    key: enable-hot-corners
    value: "false"
  - schema: org.gnome.desktop.wm.preferences
    key: focus-new-windows
    value: "'strict'"
  - schema: org.gnome.desktop.wm.preferences
    key: auto-raise
    value: "true"
  - schema: org.gnome.desktop.wm.preferences
    key: theme
    value: "'{{ theme }}'"
  - schema: org.gnome.nautilus.preferences
    key: default-folder-viewer
    value: "'list-view'"
  - schema: org.gnome.nautilus.window-state
    key: maximized
    value: "true"
  - schema: org.gnome.shell.weather
    key: automatic-location
    value: "true"
  - schema: org.gnome.desktop.screensaver
    key: user-switch-enabled
    value: "false"
  - schema: org.gnome.shell.keybindings
    key: toggle-application-view
    value: "['<Super>a']"
  - schema: org.gnome.desktop.wm.keybindings
    key: switch-windows
    value: "['<Super>Tab']"
  - schema: org.gnome.desktop.wm.keybindings
    key: switch-windows-backward
    value: "['<Shift><Super>Tab']"
  - schema: org.gnome.desktop.wm.keybindings
    key: switch-applications
    value: "['<Alt>Tab']"
  - schema: org.gnome.desktop.wm.keybindings
    key: switch-applications-backward
    value: "['<Shift><Alt>Tab']"
  - schema: org.gnome.mutter
    key: center-new-windows
    value: "true"
  - schema: org.gnome.desktop.sound
    key: allow-volume-above-100-percent
    value: "true"
  - schema: org.gnome.shell
    key: favorite-apps
    value: '["chromium-browser.desktop", "org.gnome.Terminal.desktop", "org.gnome.Nautilus.desktop", "code.desktop", "org.gnome.Software.desktop"]'
  - schema: org.gnome.desktop.background
    key: picture-uri
    value: "{{ gnome_background }}"
# - schema: org.gnome.terminal.legacy.profiles:.:b1dcc9dd-5262-4d8d-a863-c897e6d979b9
#   key: audible-bell
#   value: "true"
# - schema: org.gnome.terminal.legacy.profiles:.:b1dcc9dd-5262-4d8d-a863-c897e6d979b9
#   key: font
#   value: "{{ font }} 18"
# - schema: org.gnome.terminal.legacy.profiles:.:b1dcc9dd-5262-4d8d-a863-c897e6d979b9
#   key: use-system-font
#   value: "false"
# - schema: org.gnome.terminal.legacy.profiles:.:b1dcc9dd-5262-4d8d-a863-c897e6d979b9
#   key: use-theme-colors
#   value: "true"
# - schema: org.gnome.terminal.legacy.profiles:.:b1dcc9dd-5262-4d8d-a863-c897e6d979b9
#   key: visible-name
#   value: "Default"

gnome_install_extensions:
  # launch new instance
  - id: 600
    state: "present"
  # colorful battery indicator
  - id: 4817
    state: "present"
  # NoAnnoyance v2
  - id: 2182
    state: "present"
  # Espresso
  - id: 4135
    state: "present"
  # Sound Input & Output Device Chooser
  - id: 906
    state: "present"
  # trayIconsReloaded
  - id: 2890
    configs:
      - schema: org.gnome.shell.extensions.trayIconsReloaded
        key: icon-brightness
        value: "-10"
      - schema: org.gnome.shell.extensions.trayIconsReloaded
        key: icon-size
        value: "25"
      - schema: org.gnome.shell.extensions.trayIconsReloaded
        key: icons-limit
        value: "4"
      - schema: org.gnome.shell.extensions.trayIconsReloaded
        key: tray-margin-left
        value: "4"
    state: "present"
  # User Themes
  - id: 19
    configs:
      - schema: org.gnome.shell.extensions.user-theme
        key: name
        value: "'{{ theme }}'"
    state: "present"
