#!/bin/zsh
# Trap output to also write to log
LOG_FILE="$HOME/.sxhkd.log"
exec 3>&1 1>>${LOG_FILE} 2>&1

echo "killing current sxhkd instance if exists"

# Terminate already running instances
killall -q sxhkd

# Wait until the processes have been shut down
while pgrep -u $UID -x sxhkd >/dev/null; do sleep 1; echo "waiting for previous sxhkd to be shutdown..."; done

sxhkd -c $XDG_CONFIG_HOME/sxhkd/sxhkdrc_base $XDG_CONFIG_HOME/sxhkd/sxhkdrc_bspwm
