---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto
    - name: "taskwarrior - check taskwarrior package status"
      ansible.builtin.package:
        name: "task"
        state: "installed"
      check_mode: true
      register: pkg_status

    - name: "taskwarrior - test taskwarrior package is installed"
      ansible.builtin.assert:
        that:
          - not pkg_status.changed

    - name: "taskwarrior - check that taskrc exists"
      ansible.builtin.stat:
        path: "/root/.config/task/taskrc"
      register: stat_result

    - name: "taskwarrior - test taskrc exists"
      ansible.builtin.assert:
        that:
          - stat_result.stat.exists

    - name: "taskwarrior - check bugwarrior package status"
      ansible.builtin.stat:
        path: "/root/.local/bin/bugwarrior-pull"
      check_mode: true
      register: stat_result

    - name: "taskwarrior - test bugwarrior package is installed"
      ansible.builtin.assert:
        that:
          - not stat_result.changed
