---
# tasks file for zsh

- name: check which shell is used
  ansible.builtin.setup:
    gather_subset: "user_shell"

- name: install needed system packages
  ansible.builtin.include_role:
    name: syspackage
  vars:
    os_packages: "{{ zsh_packages }}"

- name: copy zshrc configs
  ansible.builtin.copy:
    src: zshrc
    dest: "{{ ansible_user_dir }}/.zshrc"
    force: true
    mode: preserve

- name: clone latest zplug
  ansible.builtin.git:
    repo: "https://github.com/zplug/zplug.git"
    dest: "{{ ansible_user_dir }}/.local/share/zplug"
    accept_hostkey: true
    version: 2.4.2
    force: true

- name: change default shell to zsh
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
    state: present
  become: true
  when: ansible_facts.user_shell != "/usr/bin/zsh"
