---
- name: install needed system packages
  package:
      name: picom
      state: present
  become: yes

- name: make sure destination for templates exists
  file:
      path: "{{ ansible_user_dir }}/.config/picom"
      state: directory
      mode: 0755

- name: copy configs to directory
  copy:
      src: "{{ item }}"
      dest: "{{ ansible_user_dir }}/.config/picom/"
      mode: preserve
  with_fileglob:
      - files/*
