- name: include OS specific vars
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: install aws cli tool
  ansible.builtin.include_role:
    name: syspackage
  vars:
    os_packages: "{{ aws_packages }}"

- name: make sure awscli config directory exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/aws"
    state: directory
    mode: 0755
