---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: "vim - check neovim package status"
      ansible.builtin.package:
        name: "neovim"
        state: "installed"
      check_mode: true
      register: pkg_status

    - name: "vim - test neovim package is installed"
      ansible.builtin.assert:
        that:
          - not pkg_status.changed

    - name: "vim - check that local plugins exists"
      ansible.builtin.stat:
        path: "/root/.config/nvim/config/local.plugins.yaml"
      register: stat_result

    - name: "vim - test local plugins exists"
      ansible.builtin.assert:
        that:
          - stat_result.stat.exists

    - name: "vim - check that local settings exists"
      ansible.builtin.stat:
        path: "/root/.config/nvim/config/local.vim"
      register: stat_result

    - name: "vim - test local settings exists"
      ansible.builtin.assert:
        that:
          - stat_result.stat.exists
