---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Collect only facts returned by facter
      ansible.builtin.setup:
        gather_subset:
          - "user_shell"

    - name: "zsh - check zsh package status"
      ansible.builtin.package:
        name: "zsh"
        state: "installed"
      check_mode: true
      register: pkg_status

    - name: "zsh - test zsh package is installed"
      ansible.builtin.assert:
        that:
          - not pkg_status.changed

    - name: "zsh - check that zshrv exists"
      ansible.builtin.stat:
        path: "/root/.zshrc"
      register: stat_result

    - name: "zsh - test zshrc exists"
      ansible.builtin.assert:
        that:
          - stat_result.stat.exists

    - name: "zsh - test zplug package is installed"
      ansible.builtin.stat:
        path: "/root/.local/share/zplug"
      register: stat_result

    - name: "zsh - test zplug exists"
      ansible.builtin.assert:
        that:
          - stat_result.stat.exists

    - name: "zsh - test zsh is the default shell"
      ansible.builtin.assert:
        that:
          - ansible_facts.user_shell == '/usr/bin/zsh'
