---
- name: include distro-specific vars
  include_vars: "{{ ansible_os_family }}.yml"

- name: install gnome packages
  include_role:
    name: syspackage
  vars:
    os_packages: "{{ gnome_packages }}"

- name: make sure destination for templates exists
  file:
    path: "{{ item.dest | dirname }}"
    state: directory
    mode: 0700
  with_items: "{{ gnome_files|default([]) }}"

- name: create config templates in destination
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: preserve
  with_items: "{{ gnome_files|default([]) }}"

- name: create font directories
  file:
    path: "{{ ansible_user_dir }}/.local/share/fonts/{{ item.name }}"
    state: directory
    mode: 0755
  with_items: "{{ gnome_fonts|default([]) }}"

- name: download fonts
  get_url:
    url: "{{ item.url }}"
    dest: "/tmp/{{ item.name }}.zip"
    force: true
  with_items: "{{ gnome_fonts|default([]) }}"

- name: unpack and install fonts
  unarchive:
    src: "/tmp/{{ item.name }}.zip"
    dest: "{{ ansible_user_dir }}/.local/share/fonts/{{ item.name }}"
    remote_src: true
  with_items: "{{ gnome_fonts|default([]) }}"
  notify: refresh fonts

- name: load Gnome extension information
  include_tasks: get_extension_info.yml
  with_items: "{{ gnome_install_extensions }}"

- include_tasks: install_extensions.yml
  vars:
    gnome_extension: "{{ item }}"
  loop: "{{ gnome_extensions_full }}"

- name: modify gnome settings using gsettings
  gsetting:
    user: "{{ ansible_user_id }}"
    key: "{{ item.schema }}.{{ item.key }}"
    value: "{{ item.value }}"
  with_items: "{{ gnome_config_gsettings|default([]) }}"
  become: true

- include_tasks: gedit.yml
  when: "'Adwaita' not in {{ gnome_theme }}"
