---
dependency:
  name: galaxy
  options:
    role-file: galaxy_roles/requirements.yml
    requirements-file: galaxy_roles/requirements.yml

driver:
  name: docker

platforms:
  - name: default
    image: geerlingguy/docker-fedora34-ansible:latest

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles
    TERM: xterm
  playbooks:
    converge: ../../playbook.yml

scenario:
  name: default

verifier:
  name: ansible
  additional_files_or_dirs:
    - ../../roles/*/molecule/default/verify.yml
