---
dependency:
  name: galaxy
  options:
    role-file: galaxy_roles/requirements.yml
    requirements-file: galaxy_roles/requirements.yml

driver:
  name: docker

platforms:
  - name: instance
    image: "${MOLECULE_DISTRO:-geerlingguy/docker-fedora36-ansible:latest}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles
    TERM: xterm
  playbooks:
    converge: ../../playbook.yml

scenario:
  name: default

verifier:
  name: ansible
  additional_files_or_dirs:
    - ../../roles/*/molecule/default/verify.yml
