---
- name: include OS specific vars
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: install git and relevant packages
  ansible.builtin.include_role:
    name: syspackage
  vars:
    os_packages: "{{ git_packages }}"

- name: create global git config directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/git"
    state: directory
    mode: 0755

- name: copy global git config files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.config/git/{{ item.split('/')[-1].split('.')[0] }}"
    mode: preserve
  with_fileglob:
    - files/*

- name: make sure gitconfig is up to date
  ansible.builtin.template:
    src: gitconfig.j2
    dest: "{{ ansible_user_dir }}/.config/git/config"
    mode: preserve
