---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: gather package facts
      package_facts:
        manager: auto

    - name: tmux - test tmux package is installed
      assert:
        that: "'{{ item }}' in ansible_facts.packages"
      with_items:
        - tmux

    - name: "tmux - check that tmux.conf exists"
      stat:
        path: "/root/.config/tmux/tmux.conf"
      register: stat_result

    - name: "tmux - test tmux.conf exists"
      assert:
        that:
          - stat_result.stat.exists
