---
- name: install needed system packages
  package:
      name: dunst
      state: present
  become: yes

- name: make sure destination for templates exists
  file:
      path: "{{ ansible_user_dir }}/.config/dunst"
      state: directory
      mode: 0755

- name: copy configs to directory
  template:
      src: dunstrc.j2
      dest: "{{ ansible_user_dir }}/.config/dunst/dunstrc"
      mode: preserve
