---
- name: install needed system packages
  package:
      name: polybar,nitrogen,git
      state: present
  become: yes

- name: make sure destination for templates exists
  file:
      path: "{{ ansible_user_dir }}/.config/polybar"
      state: directory
      mode: 0755

- name: copy launch.sh to directory
  copy:
      src: config
      dest: "{{ ansible_user_dir }}/.config/polybar/"
      mode: a+x

- name: copy include-modules to directory
  template:
      src: include-modules.ini.j2
      dest: "{{ ansible_user_dir }}/.config/polybar/include-modules.ini"
      mode: 0655

- name: make sure material font directory exists
  file:
      path: "{{ ansible_user_dir }}/.local/share/fonts/MaterialIcon"
      state: directory
      mode: 0755

- name: download material font
  get_url:
      url: https://github.com/material-icons/material-icons-font/blob/master/font/MaterialIcons-Outlined.ttf
      dest: "{{ ansible_user_dir }}/.local/share/fonts/MaterialIcon/MaterialIcons-Outlined.ttf"
      mode: "0644"
  notify: refresh fonts
