---
- name: include OS specific vars
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: install go and relevant packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ git_packages }}"
  become: true

- name: create global go config directory
  ansible.builtin.file:
    path: "{{ go_user_dir }}"
    state: directory
    mode: 0755
