---
- name: include OS specific vars
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: install go and relevant packages
  ansible.builtin.include_role:
    name: syspackage
  vars:
    os_packages: "{{ go_packages }}"

- name: create global go config directory
  ansible.builtin.file:
    path: "{{ go_user_dir }}"
    state: directory
    mode: 0755
