---
- name: install needed system packages
  package:
      name: "rofi"
      state: present
  become: yes

- name: make sure destination for templates exists
  file:
      path: "{{ ansible_user_dir }}/.config/rofi"
      state: directory
      mode: 0755

- name: copy launcher to config directory
  copy:
      src: config.rasi
      dest: "{{ ansible_user_dir }}/.config/rofi/"
      mode: 0644

- name: copy theme to config directory
  copy:
      src: "theme/{{ theme }}.rasi"
      dest: "{{ ansible_user_dir }}/.config/rofi/theme.rasi"
      mode: 0644
