---
- name: install needed system packages
  package:
    name: tmux
    state: present
  become: yes

- name: make sure destination for templates exists
  file:
    path: "{{ ansible_user_dir }}/.config/tmux"
    state: directory
    mode: 0755

- name: copy configs to directory
  copy:
    src: "{{ role_path }}/files/tmux.conf"
    dest: "{{ ansible_user_dir }}/.config/tmux/"
    mode: preserve

- name: install Tmux Plugin Manager
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_user_dir }}/.tmux/plugins/tpm"
    version: master

# - name: load tpm and install plugins
#   command: tmux source {{ ansible_user_dir }}/.config/tmux.conf && ~/.tmux/plugins/tpm/bin/install_plugins
#   ignore_errors: yes
#   when: true
