---
# defaults file for python

xdg_data_home: "{{ ansible_env.HOME }}/.local/share"

rbenv_repo: https://github.com/rbenv/rbenv.git

rbenv_root: "{{ xdg_data_home }}/rbenv"

rbenv_version: v1.2.0

rbenv_versions:
  - "2.7.4"

rbenv_plugins:
  - name: rbenv-update
    repo: https://github.com/rkh/rbenv-update.git
    version: master
  - name: ruby-build
    repo: https://github.com/rbenv/ruby-build.git
    version: master
  - name: rbenv-installer
    repo: https://github.com/rbenv/rbenv-installer.git
    version: main

default_ruby: 2.7.4
