---
dependency:
  name: galaxy
  options:
    role-file: ../../galaxy_roles/requirements.yml

driver:
  name: docker

lint: |
  ansible-lint

platforms:
  - name: fedora
    image: geerlingguy/docker-fedora36-ansible:latest
provisioner:
  name: ansible
  config_options:
    defaults:
      verbosity: 1
verifier:
  name: ansible

scenario:
  name: default
