---
dependency:
  name: galaxy
  options:
    role-file: ../../galaxy_roles/requirements.yml
driver:
  name: docker
lint: |
  ansible-lint --exclude ../../../../.ansible/roles
platforms:
  - name: default
    image: geerlingguy/docker-fedora35-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    override_command: true
    privileged: true
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: ansible
