---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: "docker - check docker package status"
      ansible.builtin.package:
        name: docker
        state: installed
      check_mode: true
      register: pkg_status

    - name: "docker - test docker package is installed"
      ansible.builtin.assert:
        that:
          - not pkg_status.changed
