---
- name: install required packages
  become: yes
  package:
      name: "{{ lightdm_packages }}"
      state: latest
      update_cache: yes

- name: create config and theme directories
  become: yes
  file:
      path: "{{ item }}"
      state: directory
      mode: 0755
  loop:
      - "/etc/lightdm"
      - "/usr/share/lightdm-webkit/themes"

- name: clone theme repo
  become: yes
  git:
      repo: "{{ light_dm_theme_repo }}"
      dest: "/usr/share/lightdm-webkit/themes/"

- name: create lightdm config file
  become: yes
  copy:
      src: "lightdm.conf"
      dest: "/etc/lightdm/lightdm.conf"
      mode: 0644

- name: create lightdm-webkit2-greeter config file
  become: yes
  template:
      src: "greeter.j2"
      dest: "/etc/lightdm/lightdm-webkit2-greeter.conf"
      mode: 0644
