---
- name: Verify
  hosts: all
  gather_facts: true

  tasks:
    - name: "python - check for pyenv"
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.config/pyenv"
      register: stat_result

    - name: "python - check that pyenv exists"
      ansible.builtin.assert:
        that:
          - stat_result.stat.exists

    - name: "python - run pyenv --version"
      ansible.builtin.command: "{{ ansible_env.HOME }}/.config/pyenv/bin/pyenv --version | grep pyenv"
      ignore_errors: true
      register: cmd_out

    - name: "python - check pyenv --version output"
      ansible.builtin.assert:
        that:
          - cmd_out is succeeded
