---
- name: Verify
  hosts: all
  gather_facts: true

  tasks:
      - name: "python - check for pyenv"
        stat:
            path: "{{ ansible_env.HOME }}/.config/pyenv"
        register: stat_result

      - name: "python - check that pyenv exists"
        assert:
            that:
                - stat_result.stat.exists

      - name: "python - run pyenv --version"
        shell: "{{ ansible_env.HOME }}/.config/pyenv/bin/pyenv --version | grep pyenv"
        ignore_errors: true
        register: cmd_out

      - name: "python - check pyenv --version output"
        assert:
            that:
                - cmd_out is succeeded
