---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: "vscode - check vscode package status"
      ansible.builtin.package:
        name: "code"
        state: "installed"
      check_mode: true
      register: pkg_status

    - name: "vscode - test vscode package is installed"
      ansible.builtin.assert:
        that:
          - not pkg_status.changed
