---
# handlers file for python

- name: set ruby {{ default_ruby }} for system
  ansible.builtin.command: "{{ rbenv_root }}/bin/rbenv global {{ default_ruby }}"
  args:
    creates: "{{ rbenv_root }}/versions/version"
  environment:
    RBENV_ROOT: "{{ rbenv_root }}"
