---
dependency:
  name: galaxy
driver:
  name: docker
# lint: |
#   ansible-lint
platforms:
  - name: instance
    image: quay.io/fedora/fedora:latest
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
