---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: "gnome - check gnome package status"
      ansible.builtin.package:
        name: "gnome-shell"
        state: "installed"
      check_mode: true
      register: pkg_status

    - name: "gnome - test gnome package is installed"
      ansible.builtin.assert:
        that:
          - not pkg_status.changed
