---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
      - name: "gnome - check gnome package status"
        package:
            name: "gnome-shell"
            state: "installed"
        check_mode: yes
        register: pkg_status

      - name: "gnome - test gnome package is installed"
        assert:
            that:
                - not pkg_status.changed
