---
rbenv_packages:
  - git-core
  - curl
  - gcc
  - gcc-c++
  - openssl-devel
  - libyaml-devel
  - readline
  - readline-devel
  - zlib
  - zlib-devel
  - libffi-devel
  - git
  - bzip2
  - make
  - patch
  - autoconf
  - libtool
  - bison
  - sqlite-devel
