---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
      - name: "sxhkd - check sxhkd package status"
        package:
            name: "sxhkd"
            state: "installed"
        check_mode: yes
        register: pkg_status

      - name: "sxhkd - test sxhkd package is installed"
        assert:
            that:
                - not pkg_status.changed

      - name: "sxhkd - check that sxhkdrc exists"
        stat:
            path: "/root/.config/sxhkd/sxhkdrc"
        register: stat_result

      - name: "sxhkd - test sxhkdrc exists"
        assert:
            that:
                - stat_result.stat.exists
