---
# tasks file for vim

- name: install needed system packages
  ansible.builtin.include_role:
    name: syspackage
  vars:
    os_packages: "{{ vim_packages }}"

- name: ensure pip_install_packages are installed for pip3.
  ansible.builtin.pip:
    name: "{{ python_pip }}"
    executable: "pip3"
    extra_args: --user

- name: install NPM packages
  ansible.builtin.npm:
    name: "{{ item }}"
    global: true
    state: present
  environment:
    #       XDG_CONFIG_HOME: "{{ ansible_user_dir }}/.config/"
    #       NVM_DIR: "{{ nvm_link_dir }}"
    PATH: "{{ lookup('env', 'PATH') }}:{{ nvm_link_dir }}/versions/node/v{{ node_version }}/bin"
  with_items: "{{ npm_packages }}"

- name: clone lastest vim-config
  ansible.builtin.git:
    repo: "{{ vim_repo }}"
    dest: "{{ ansible_user_dir }}/.config/nvim"
    update: false
    accept_hostkey: true
    version: master
  register: vimconfig

- name: add local vim settings
  ansible.builtin.copy:
    src: local.vim
    dest: "{{ ansible_user_dir }}/.config/nvim/config/local.vim"
    local_follow: true
    mode: preserve

- name: add local plugin settings
  ansible.builtin.copy:
    src: local.plugins.yaml
    dest: "{{ ansible_user_dir }}/.config/nvim/config/local.plugins.yaml"
    local_follow: true
    mode: preserve
