- name: include OS specific vars
  include_vars: "{{ ansible_os_family }}.yml"

- name: install alacritty package
  include_role:
    name: syspackage
  vars:
    os_packages: "{{ alacritty_packages }}"
    external_repos: "{{ alacritty_repos }}"

- name: make sure destination for templates exists
  file:
    path: "{{ ansible_user_dir }}/.config/alacritty"
    state: directory
    mode: 0755

- name: setup alacritty yml
  template:
    src: alacritty.j2
    dest: "{{ ansible_user_dir }}/.config/alacritty/alacritty.yml"
    mode: preserve
