- name: include OS specific vars
  include_vars: "{{ ansible_os_family }}.yml"

- name: install xmonad package
  include_role:
    name: syspackage
  vars:
    os_packages: "{{ xmonad_packages }}"

- name: make sure destination for templates exists
  file:
    path: "{{ ansible_user_dir }}/.config/xmonad"
    state: directory
    mode: 0755

- name: setup xmonad.hs config file
  template:
    src: xmonad.hs.j2
    dest: "{{ ansible_user_dir }}/.config/xmonad/xmonad.hs"
    mode: preserve
