---
- name: include OS specific vars
  include_vars: "{{ ansible_os_family }}.yml"

- name: install needed system packages
  package:
      name: "{{ item }}"
      state: present
  with_items: "{{ rbenv_packages }}"
  become: yes

- include_tasks: rbenv.yml
  loop: "{{ rbenv_versions }}"
  loop_control:
      loop_var: rbenv_package_loop
