---
- name: checkout rbenv_repo for system
  ansible.builtin.git:
    repo: "{{ rbenv_repo }}"
    dest: "{{ rbenv_root }}"
    accept_hostkey: true
    force: true
    version: "{{ rbenv_version }}"

- name: create plugins directory for system
  ansible.builtin.file:
    path: "{{ rbenv_root }}/plugins"
    state: directory
    mode: "0755"

- name: install plugins for system
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ rbenv_root }}/plugins/{{ item.name }}"
    accept_hostkey: true
    force: true
    version: "{{ item.version }}"
  with_items: "{{ rbenv_plugins }}"

- name: install ruby versions for system
  ansible.builtin.command:
    cmd: "{{ rbenv_root }}/bin/rbenv install --skip-existing {{ item }}"
    creates: "{{ rbenv_root }}/versions/{{ item }}"
  environment:
    RBENV_ROOT: "{{ rbenv_root }}"
  with_items:
    - "{{ rbenv_versions }}"

- name: set ruby {{ default_ruby }} for system
  ansible.builtin.command: "{{ rbenv_root }}/bin/rbenv global {{ default_ruby }}"
  args:
    creates: "{{ rbenv_root }}/versions/version"
  environment:
    RBENV_ROOT: "{{ rbenv_root }}"
