---
- name: Converge
  hosts: all
  tasks:
    - name: run packages for rpm fusion
      ansible.builtin.include_role:
        name: packages
    - name: include powersave
      ansible.builtin.include_role:
        name: powersave
