---
dependency:
  name: galaxy
  options:
    role-file: ../../galaxy_roles/requirements.yml
driver:
  name: docker
lint: |
  ansible-lint --exclude ../../../../.ansible/roles
platforms:
  - name: instance
    image: quay.io/fedora/fedora:latest
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
