---
dependency:
  name: galaxy
  options:
    role-file: ../../galaxy_roles/requirements.yml
driver:
  name: docker
lint: |
  ansible-lint --exclude ../../../../.ansible/roles
platforms:
  - name: fedora
    image: geerlingguy/docker-fedora36-ansible:latest
provisioner:
  name: ansible
verifier:
  name: ansible
