---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: "powersave - check thermald package status"
      ansible.builtin.package:
        name: "thermald"
        state: "installed"
      check_mode: true
      register: pkg_status

    - name: "powersave - test thermald package is installed"
      ansible.builtin.assert:
        that:
          - not pkg_status.changed
