---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: "powersave - check tlp package status"
      ansible.builtin.package:
        name: "tlp"
        state: "installed"
      check_mode: true
      register: pkg_status

    - name: "powersave - test tlp package is installed"
      ansible.builtin.assert:
        that:
          - not pkg_status.changed

    - name: "powersave - check powertop package status"
      ansible.builtin.package:
        name: "powertop"
        state: "installed"
      check_mode: true
      register: pkg_status

    - name: "powersave - test powertop package is installed"
      ansible.builtin.assert:
        that:
          - not pkg_status.changed
